Avoid exception when registering shortcut (#201)
* Fix undefined attribute _labels_key

Accessing the property `model.labels_key` gave an `AttributeError("'ImageModel' object has no attribute '_labels_key'")`

* Avoid exception when key binding collides with existing

If the shortcut is already registered, Napari does not warn but raise an error. To avoid crashing Napari, we must provide the override argument (no matter whether preserving existing or overriding with the new command).