Issue #180 (#205)
* Multi table (#196)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* Revert "Multi table (#196)" (#197)

This reverts commit aa56ccaccd55a9446cb96cb2c76d9ec7fbd97f9a.

* Avoid exception when registering shortcut (#201)

* Fix undefined attribute _labels_key

Accessing the property `model.labels_key` gave an `AttributeError("'ImageModel' object has no attribute '_labels_key'")`

* Avoid exception when key binding collides with existing

If the shortcut is already registered, Napari does not warn but raise an error. To avoid crashing Napari, we must provide the override argument (no matter whether preserving existing or overriding with the new command).

* add color by in adata view

* remove _scale from model

* remove points coordinates

* remove point_diameter

* remove spot diameter

---------

Co-authored-by: aeisenbarth <54448967+aeisenbarth@users.noreply.github.com>
Co-authored-by: Luca Marconato <m.lucalmer@gmail.com>