Multi table (#198) (#199)
* Multi table (#198)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* Multi table (#200)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* remove legacy squidpy

* remove legacy squidpy

* remove coordinates

* fix tests

* silence warnings

* fix last tests

* fix mypy

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

* Multi table (#202)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* remove legacy squidpy

* remove legacy squidpy

* remove coordinates

* fix tests

* silence warnings

* fix last tests

* fix mypy

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* add table for adatascatter

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

* Fix adding layer without table

* fix removing layer

* fix wrong point size when affine specified (#193)

* add color by in adata view (#204)

* Issue #180 (#205)

* Multi table (#196)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* Revert "Multi table (#196)" (#197)

This reverts commit aa56ccaccd55a9446cb96cb2c76d9ec7fbd97f9a.

* Avoid exception when registering shortcut (#201)

* Fix undefined attribute _labels_key

Accessing the property `model.labels_key` gave an `AttributeError("'ImageModel' object has no attribute '_labels_key'")`

* Avoid exception when key binding collides with existing

If the shortcut is already registered, Napari does not warn but raise an error. To avoid crashing Napari, we must provide the override argument (no matter whether preserving existing or overriding with the new command).

* add color by in adata view

* remove _scale from model

* remove points coordinates

* remove point_diameter

* remove spot diameter

---------

Co-authored-by: aeisenbarth <54448967+aeisenbarth@users.noreply.github.com>
Co-authored-by: Luca Marconato <m.lucalmer@gmail.com>

* Issue #192 (#207)

* Multi table (#196)

* update napari dependency

* change deprecated is_categorical_dtype

* Iinitial table widget

* add table_names to model

* More self explainable function name

* allow changing tables

* fix some tests

* Fixed tests

* Revert "Multi table (#196)" (#197)

This reverts commit aa56ccaccd55a9446cb96cb2c76d9ec7fbd97f9a.

* Avoid exception when registering shortcut (#201)

* Fix undefined attribute _labels_key

Accessing the property `model.labels_key` gave an `AttributeError("'ImageModel' object has no attribute '_labels_key'")`

* Avoid exception when key binding collides with existing

If the shortcut is already registered, Napari does not warn but raise an error. To avoid crashing Napari, we must provide the override argument (no matter whether preserving existing or overriding with the new command).

* add color by in adata view

* remove _scale from model

* remove points coordinates

* remove point_diameter

* remove spot diameter

* fix #192

---------

Co-authored-by: aeisenbarth <54448967+aeisenbarth@users.noreply.github.com>
Co-authored-by: Luca Marconato <m.lucalmer@gmail.com>

* Test spatialelement table join (#208)

* fixed all the non-cytassist images

* refactor get_init_table_list

* fix permutation

* use join

* use join for view

* change hardcoded sample threshold

* bunch of updates

* adjust test

* change into left join

* change into left join

* random hex colors

* get actual index

* change indices and adata

* match rows left

* fix joins

* rename to vars

* fix color by

* fix radii

* pass cs

* fix _calc_default_radii()

* fix tests

* improve speed test

* removed comments

* added code to show circles as ellipses

* correct point layer size after scaling

* fix labels color by

* fix mibitof example

* last bug fixes

* initial step points columns

* add dask import back

* fix points columns

---------

Co-authored-by: wmv_hpomen <w-mv@hotmail.com>
Co-authored-by: Wouter-Michiel Vierdag <michiel.vierdag@embl.de>

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: LucaMarconato <2664412+LucaMarconato@users.noreply.github.com>
Co-authored-by: aeisenbarth <54448967+aeisenbarth@users.noreply.github.com>
Co-authored-by: Luca Marconato <m.lucalmer@gmail.com>